package apimodels

const (
	Bulgarian          = "bg"
	Czech              = "cs"
	Danish             = "da"
	German             = "de"
	English            = "en"
	EnglishUs          = "en-US"
	Spanish            = "es"
	SpanishLatin       = "es-419"
	Finnish            = "fi"
	French             = "fr"
	Indonesian         = "id"
	Italian            = "it"
	Hungarian          = "hu"
	Japan              = "ja"
	Korean             = "ko"
	Malay              = "ms"
	Norwegian          = "nb"
	Dutch              = "nl"
	Polish             = "pl"
	Portuguese         = "pt"
	PortugueseBrazil   = "pt-BR"
	Russian            = "ru"
	Serbian            = "sr"
	Swedish            = "sv"
	Turkish            = "tr"
	Chinese            = "zh"
	ChineseTraditional = "zh-TW"
)
